services:
  prometheus:
    cpus: "0.25"
    mem_limit: 512M
    memswap_limit: 512M

  grafana:
    cpus: "0.25"
    mem_limit: 512M
    memswap_limit: 512M

  k6:
    cpus: "0.50"
    mem_limit: 512M
    memswap_limit: 512M
