spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Redis 설정 (테스트 환경)
  data:
    redis:
      host: localhost
      port: 6379

  # Cache 설정
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10분 (밀리초)
      cache-null-values: false

initdata:
  enabled: true
